### PR TITLE
[Important][Android] Fix crash null target view when use with react-native-navigation MODAL

### PR DESCRIPTION
**Pull request by congnguyen91**
[ANDROID]
- Now no error with tutorial pop up behind show behind modal with react-navigation.
- Can resolve null view reference pass from React native JS to native code.

@prscX this is an important fix for android with crash null view
- Please check & merge it & release if you can 👯‍♂️ 

Thanks,
Cong

### CODE REVIEW

**Comment by congnguyen91** [comment]
@prscX  Please write it on ReadMe.
If you have problems with "(Android) Trying to resolve view with tag which doesn't exist" or "can't resolve tag",...
Please add PROPERRTY: "collapsable=false" on your View, Touchable. It has optimized on react-native.
link:
https://github.com/gre/react-native-view-shot/issues/7
https://facebook.github.io/react-native/docs/view.html#collapsable

Be aware of component with stateless - some issue, ref on it

**Comment by prscX** [comment]
Many Thanks @congnguyen91 for effort and PR. 

If we specify prop: `collapasable: false` to our View. Then also the `Dialog` changes which you have done in Android native is required?

Thanks
Pranav

**Comment by congnguyen91** [comment]
@prscX  require :) some bugs happen like Tutorial Popup is behind screen of target like Modal.
Let's put our popup on the top of screen. Not be overrided by Modal, other Dialog

**Comment by prscX** [comment]
Many Thanks @congnguyen91 for the PR. I have merged the same and also referred the issue in `README`.

Thanks
Pranav

**Comment by prscX** [comment]
Hi @congnguyen91, I have pushed the release with V0.0.3, can you please install and verify the same:

[V0.0.3](https://github.com/prscX/react-native-app-tour/releases/tag/v0.0.3)

Thanks
Pranav

**Pull request merged**
