### PR TITLE
New Features - SKIP BUTTON

### PR DESCRIPTION
**Pull request by congnguyen91**
Hi @prscX  this merge request to announce that:

- Now We have a skip button for skipping app tour
- Please update my fork pod path on Read Me (sorry for this inconvenience)
```
pod 'MaterialShowcase',:git => 'https://github.com/congnguyen91/material-showcase-ios.git', :commit =>'985d330'
```

* important note for using skip button to avoid android bug
1. transparentTarget:true
2. dimColor='#000000'

- More & more task to do with this like prevent stuck with dialog (if have, prevent crash - add try catch ...) => later. 
Thanks,
Cong

### CODE REVIEW

**Comment by congnguyen91** [comment]
- Please help me update ReadMe :) if you can
Thank @prscX

**Comment by congnguyen91** [comment]
@prscX  I have done for margin skip button - default 20
also can margin top, left, right, bottom - horizontal, vertical

- Please check pod path of example for noting on ReadMe - Maybe I also update ReadMe note tonight.
- Let's check & release first

**Comment by prscX** [comment]
WOW, Many Many Thanks @congnguyen91 for the PR. Please give me sometime I will review the same.

Thanks
</ Pranav >

**Comment by congnguyen91** [comment]
@prscX thanks 
I have done my part :)  

Give your feedback if you want to make some change. There are some conflicting file now. But I think you can do it with your pod change :+1: 

Thanks,
Cong

**Comment by anniewey** [comment]
@prscX is this ready to merge yet? need this feature in my app. 
btw thanks @congnguyen91 for the enhancement!

**Comment by congnguyen91** [comment]
@anniewey  Thanks for your interesting!
I & @prscX have a desire for avoiding native lib fork on iOS. Wanna add a script to download the forked material case native as embed lib. 

It is easy for developers to updating the module and prevent error from updating like a locked version.
(Instead of changing pod like )
```
 pod 'MaterialShowcase',:git => 'https://github.com/congnguyen91/material-showcase-ios.git', :commit =>'ecca35b'
```

So it is in pending/enhencement status util we resolve it. You can use it right now as my example :)
Sorry for this inconvenience. 
How do you think of it?  @prscX?
Thanks,
Cong

**Comment by Noitidart** [comment]
Hi all, I was eager to use the `isRect` on ios and android. I was wondering how far this PR is away from merging?

Edit:
oooops, excuse my comment please Im seeing folks make comments just an hour ago.

**Comment by prscX** [comment]
My apologies for the delay in response.

Thanks @congnguyen91 for sharing the blog's related to scripts.

Hi @Noitidart,

I have still not decided on how to enable skip feature through this PR, however I am exploring ways in order to enable rect targets.

I will keep you posted about the updates.

Thanks
</ Pranav >

**Comment by Noitidart** [comment]
Sincerest thanks brother. I will be uploading my app to the play store and ios store soon that uses this. I know I love seeing how people use my stuff. I hope to thank you folks for this amazing work by showing you how valueable this is by showing how I use it! :)

**Comment by prscX** [comment]
Hi @congnguyen91, 

Is `isRect` a custom implementation you have done for Android? I was look at [KeepSafe/TapTargetView](https://github.com/KeepSafe/TapTargetView) source but could not find any API's similar to `rectTarget` and `rectTargetBorderRadius`

Thanks
</ Pranav >

**Comment by prscX** [comment]
@congnguyen91: For iOS I have tried to set `setTargetHolderRadius: 0` but circle is still visible. Have you fixed any issues related to this?

Thanks,
</ Pranav >

**Comment by congnguyen91** [comment]
@pranavchauhan It seem be fine on android 
```
if (target.isRectTarget()) {
      RectF rectF = new RectF(targetBounds.left, targetBounds.top, targetBounds.right, targetBounds.bottom);
      c.drawRoundRect(rectF, target.getRectTargetBorderRadius(), target.getRectTargetBorderRadius(),targetCirclePaint );
    } else {
      /// No rect bound
      if (targetCirclePulseAlpha > 0) {
        targetCirclePulsePaint.setAlpha(targetCirclePulseAlpha);
        c.drawCircle(targetBounds.centerX(), targetBounds.centerY(),
                targetCirclePulseRadius, targetCirclePulsePaint);
      }
      c.drawCircle(targetBounds.centerX(), targetBounds.centerY(),
              targetCircleRadius, targetCirclePaint);
    }
```
Please follow this https://github.com/congnguyen91/TapTargetView

**Comment by congnguyen91** [comment]
This is my fork path:     compile 'com.github.congnguyen91:TapTargetView:30b49da'

**Comment by prscX** [comment]
Thanks @congnguyen91 for sharing the snippet reference. I will try the same and will share the results.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @congnguyen91: Looks like this is a custom implementation done specific in order to handle isReact targets. The original fork does not contain/support rect targets.

I am really confused, how we can enable these useful features (rect target, skip) when the original fork is not supporting, because maintaining/upgrading these implementation are really painful.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @congnguyen91  + @Noitidart: I have found a great solution in order to achieve rect targets.

Please refer Android: TapTargetView README, where they have defined how to achieve custom targets. I am going to try this and share the results with you.

Thanks
</ Pranav >

**Comment by Noitidart** [comment]
Wow super cool!

**Comment by congnguyen91** [comment]
@prscX There are many supper cool features on my fork iOS, android lib - On Android, you can test my fork by replace the android ref lib on the gradle file.

      If you can resolve the iOS native  lib pod ref to my fork automatically 
      - easy for devs. I & you can handle & merge it frequently :D  
      Try it in your free time.

Thanks,
Cong

**Comment by congnguyen91** [comment]
Ah, You are also a collaborator in my native lib both android & iOS. You can change & apply if you want to improve libs :)
https://github.com/congnguyen91/material-showcase-ios
https://github.com/congnguyen91/TapTargetView

**Comment by aMarCruz** [comment]
@prscX , seems TapTargetView will not support rectangular shapes: https://github.com/KeepSafe/TapTargetView/issues/231

:confused:

I've tried [FancyShowCaseView](https://github.com/faruktoptas/FancyShowCaseView) that supports rectangles but no description. You can add the description within the title using Spanned text, but still the API is very different and I think TapTargetView is better.

Maybe it would be best to insert a modified version of TapTargetView directly into this library. Anyway it seems that Google has removed the specification of "on feature discovery".

**Comment by ShivamJoker** [comment]
when this is going to be merged ?
I see in the main TapTarget library also we have now rectangle function.

**Comment by prscX** [comment]
Thanks @congnguyen91 for Effort and PR.

We can not merge this PR because it will be difficult to maintain the custom implementation and feature which is not supported by the native library. However, in case someone wants to use skip functionality they use @congnguyen91 repo for the same.

Closing this PR.

Thanks,
Pranav

**Comment by ShivamJoker** [comment]
@prscX you woke after 4 years?

**Comment by prscX** [comment]
My apologies. I was not able to cope with personal, professional and open source contribution all together. I hope you would understand that. 

Just looking at the open PR's and trying to review and close if can't be merged.

Thanks,
Pranav

**Comment by congnguyen91** [comment]
huhm - Do you want me to update the PR and feature @prscX  ^^?

**Pull request closed without merging**
