### PR TITLE
Prevent multiple addition of same component in the tour

### PR DESCRIPTION
**Pull request by ankag94**
This will allow a component to appear in show sequence of tour only once, thus maintain consistency during multiple re-renderings or any iterative calls.

### CODE REVIEW

**Comment by prscX** [comment]
Thanks a lot @ankag94 for the effort and PR.

 `+` [@congnguyen91, @Noitidart]

I too have faced this issue when the ref function is invoked multiple time due to re-rendering and AppSequence is adding the same ref multiple times. I think the effort @ankag94 will resolve this issue.

However it will have a breaking changes in the existing apps. Each target should provide a key, this is even recommend by ReactJS guidelines.

Please feel free to share your views on the same.

Thanks
</ Pranav >

**Comment by congnguyen91** [comment]
Hi all,
This solution sounds good :) => we can call it "appTourId" , should mandatory.  => Write it in read me - Why should we do it - avoid duplicate.

Another solution is generating KEY/ID by TITLE => this is bad with some weird languages -> hard to debug and we can miss the targets has the same TITLE.

= WITH THIS REQUEST
We should check/handle crash  if it is null or not when we add/set new in our lib like appTourTarget.key ? .....
```
add(appTourTarget) {
    // Be careful with the second - maybe ref null => target null
    // check if appTourTarget is null - appTourTarget.key is null ?
    this.appTourTargets.set(appTourTarget.key, appTourTarget);
}
```
I suggest one property "appTourOrder" => why this? At the moment Component are arranged in render method then the ref => And We don't want to change the order of the elements in render method.
```
static ShowSequence(sequence) {
    let appTourTargets = sequence.getAll();

    /// Process the order of app tour element here 
   ///=======
   ///
    RNAppTour.ShowSequence(viewIds, props);
}
```

Thanks,
Cong

**Comment by prscX** [comment]
Thanks a lot @congnguyen91 for sharing your valuable feedbacks.

- It definitely make sense to add a preliminary check for the key validation. 
- We can access component `key` which is generated by React or even we can provide while creating a Component instance:

```javascript
<Component
 key={'component_key'} 
/>
```
- If the key is not provided or `undefined`, we can throw error.

- @ankag94: Thanks for providing solution for duplicate views issue. As suggested by @congnguyen91 can you please enhance API in order to add support for `order` as well.  

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @ankag94: I have made few changes w.r.t preliminary validation. I am merging the same.

I will be working on adding order property and post that I will push the release.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @ankag94: I have pushed a release with [V0.0.10](https://github.com/prscX/react-native-app-tour/releases/tag/v0.0.10). Can you please download and verify the same.

Please note below properties are added as a mandatory fields:
- Added `order` mandatory property for each target
- Each component which is to be rendered in the tour should have a `key` prop. It is mandatory.

Please let me know in case you face any issues.

Thanks
</ Pranav >

**Pull request merged**
