### PR TITLE
Add 'order' property for target

### PR DESCRIPTION
**Pull request by ntcong91**
- Devs can add the order of target like: "order: 2"

### CODE REVIEW

**Comment by ntcong91** [comment]
@prscX  LOL :)) Have you been updating order property?

**Comment by ntcong91** [comment]
Hi @prscX, 

With my solution - you can sort with mixing order and unorder items. Try it.

Thanks,
Cong

**Comment by prscX** [comment]
Thanks a lot @ntcong91 for the effort and PR.

Oops, I have enabled `order` property just now. This was with reference to [PR: 22](https://github.com/prscX/react-native-app-tour/pull/22).

Can you please validate and try the same `order` implementation. We have already made mandatory to provide `key` prop for all the tour components.

Thanks
</ Pranav >

**Comment by ntcong91** [comment]
Hi @prscX ,
- I close my request -
- You can test my code later
```
    const items = sequence.getAll();
    const appTourTargets = new Map(
      [...items.entries()].sort((a, b) => {
        return a[1].props.order - b[1].props.order;
      })
    );
```

Thanks,
Cong

**Comment by prscX** [comment]
Oh, @ntcong91 and @congnguyen91 id's are same is it?

Thanks 
</ Pranav>

**Comment by ntcong91** [comment]
Yes @prscX ,

Cause of @congnguyen91  is the owner for another fork now. I use another account :)

**Pull request closed without merging**
